package com.weekly.assignment02.GuitarApp;


public enum Wood {
    INDIAN_ROSEWOOD, BRAZILIAN_ROSEWOOD, MAHOGANY, MAPLE,
    COCOBOLO, CEDAR, ALDER, SITKA, ADIRONDACK, SPRUCE, ROSEWOOD, NATO, ASH;
}
